name: "Linux"
on:
  push:
    branches: [ master ]
  pull_request:
    # branches: [ master ]

jobs:
  Linux-GCC:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        cxx: ['7', '13']
    env:
      CMAKE_OPTIONS: -DDEV_MODE=ON -DBUILD_TESTING=ON -G Ninja
    steps:
      - uses: lukka/get-cmake@latest
      - uses: egor-tensin/setup-gcc@v1
        with:
          version: ${{matrix.cxx}}

      - name: Get pushed code
        uses: actions/checkout@v4

      - name: Configure
        run: cmake -S . -B _build ${{ env.CMAKE_OPTIONS }} -DCMAKE_INSTALL_PREFIX:STRING=${GITHUB_WORKSPACE}/_built

      - name: Build
        run: cmake --build _build --parallel

      - name: Test installation
        run: cmake --install _build --prefix ${GITHUB_WORKSPACE}/_built

      - name: Run tests
        run: ctest --test-dir _build
  Linux-Clang:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        cxx: ['7', '18']
    env:
      CMAKE_OPTIONS: -DDEV_MODE=ON -DBUILD_TESTING=ON -G Ninja -DCMAKE_CXX_FLAGS="-stdlib=libc++"
    steps:
      - uses: lukka/get-cmake@latest

      - name: Install libc++
        run: |
          wget -qO - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository --yes --update deb http://apt.llvm.org/focal/ llvm-toolchain-focal main
          sudo apt-get update
          sudo apt install -y libc++abi-${{matrix.cxx}}-dev libc++-${{matrix.cxx}}-dev

      - name: Get pushed code
        uses: actions/checkout@v4

      - name: Configure
        run: cmake -S . -B _build ${{ env.CMAKE_OPTIONS }} -DCMAKE_INSTALL_PREFIX:STRING=${GITHUB_WORKSPACE}/_built

      - name: Build
        run: cmake --build _build --parallel

      - name: Test installation
        run: cmake --install _build --prefix ${GITHUB_WORKSPACE}/_built

      - name: Run tests
        run: ctest --test-dir _build
  Alpine:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ['armhf']
    env:
      CMAKE_OPTIONS: -DDEV_MODE=ON -DBUILD_TESTING=ON
    defaults:
      run:
        shell: alpine.sh {0}
    steps:
      - name: Get pushed code
        uses: actions/checkout@v4

      - uses: jirutka/setup-alpine@v1
        with:
          branch: edge
          arch: ${{matrix.platform}}
          packages: >
            build-base cmake

      - name: Configure
        run: cmake -S . -B _build ${{ env.CMAKE_OPTIONS }} -DCMAKE_INSTALL_PREFIX:STRING=${GITHUB_WORKSPACE}/_built

      - name: Build
        run: cmake --build _build --parallel

      - name: Test installation
        run: cmake --install _build --prefix ${GITHUB_WORKSPACE}/_built

      - name: Run tests
        run: ctest --test-dir _build
