name: "Linux"
on:
  push:
    branches: [ master ]
  pull_request:
    # branches: [ master ]

jobs:
  Latest:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        cxx: ['g++-14', 'clang++-18']
    env:
      CMAKE_OPTIONS: -DDEV_MODE=ON -DBUILD_TESTING=ON -G Ninja
      CXX: ${{matrix.cxx}}
    steps:
      - name: list compilers
        run: dpkg --list | grep compiler

      - name: Get pushed code
        uses: actions/checkout@v4

      - name: Configure
        run: cmake -S . -B _build ${{ env.CMAKE_OPTIONS }} -DCMAKE_INSTALL_PREFIX:STRING=${GITHUB_WORKSPACE}/_built

      - name: Build
        run: cmake --build _build --parallel

      - name: Test installation
        run: cmake --install _build --prefix ${GITHUB_WORKSPACE}/_built

      - name: Run tests
        run: ctest --test-dir _build

  Oldest:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        cxx: ['g++-9', 'clang++-13']
    env:
      CMAKE_OPTIONS: -DDEV_MODE=ON -DBUILD_TESTING=ON
      CXX: ${{matrix.cxx}}
    steps:
      - name: list compilers
        run: dpkg --list | grep compiler

      - name: install ${{matrix.cxx}}
        run: |
          sudo add-apt-repository --yes --update ppa:ubuntu-toolchain-r/test
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends ${{matrix.cxx}}

      - name: Get pushed code
        uses: actions/checkout@v4

      - name: Configure
        run: cmake -S . -B _build ${{ env.CMAKE_OPTIONS }} -DCMAKE_INSTALL_PREFIX:STRING=${GITHUB_WORKSPACE}/_built

      - name: Build
        run: cmake --build _build --parallel

      - name: Test installation
        run: cmake --install _build --prefix ${GITHUB_WORKSPACE}/_built

      - name: Run tests
        run: ctest --test-dir _build

  Alpine:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ['armhf']
    env:
      CMAKE_OPTIONS: -DDEV_MODE=ON -DBUILD_TESTING=ON
    defaults:
      run:
        shell: alpine.sh {0}
    steps:
      - name: Get pushed code
        uses: actions/checkout@v4

      - uses: jirutka/setup-alpine@v1
        with:
          branch: edge
          arch: ${{matrix.platform}}
          packages: >
            build-base cmake

      - name: Configure
        run: cmake -S . -B _build ${{ env.CMAKE_OPTIONS }} -DCMAKE_INSTALL_PREFIX:STRING=${GITHUB_WORKSPACE}/_built

      - name: Build
        run: cmake --build _build --parallel

      - name: Test installation
        run: cmake --install _build --prefix ${GITHUB_WORKSPACE}/_built

      - name: Run tests
        run: ctest --test-dir _build

  s390X-BigEndian:
    runs-on: ubuntu-latest
    env:
      CMAKE_OPTIONS: -DDEV_MODE=ON -DBUILD_TESTING=ON -DCMAKE_SYSTEM_PROCESSOR=s390x -DCMAKE_CROSSCOMPILING_EMULATOR="qemu-s390x;-L;/usr/s390x-linux-gnu/" -DCMAKE_CXX_COMPILER=s390x-linux-gnu-g++ -G Ninja
    steps:
      - name: install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends qemu-user crossbuild-essential-s390x qemu-system-s390x

      - name: list compilers
        run: dpkg --list | grep compiler

      - name: Get pushed code
        uses: actions/checkout@v4

      - name: Configure
        run: cmake -S . -B _build ${{ env.CMAKE_OPTIONS }} -DCMAKE_INSTALL_PREFIX:STRING=${GITHUB_WORKSPACE}/_built

      - name: Build
        run: cmake --build _build --parallel

      - name: Test installation
        run: cmake --install _build --prefix ${GITHUB_WORKSPACE}/_built

      - name: Run tests
        run: ctest --test-dir _build
