name: "Linux"
on:
  push:
    branches: [ master ]
  pull_request:
    # branches: [ master ]

jobs:
  build_libebml:
    name: libebml
    runs-on: ubuntu-latest
    env:
      CMAKE_OPTIONS: -DDEV_MODE=ON -DBUILD_TESTING=ON
    steps:
      - uses: lukka/get-cmake@latest

      - name: Get pushed code
        uses: actions/checkout@v4

      - name: Configure
        run: cmake -S . -B _build ${{ env.CMAKE_OPTIONS }} -DCMAKE_INSTALL_PREFIX:STRING=${GITHUB_WORKSPACE}/_built

      - name: Build
        run: cmake --build _build --parallel

      - name: Test installation
        run: cmake --install _build --prefix ${GITHUB_WORKSPACE}/_built

      - name: Run tests
        run: ctest --test-dir _build
