name: "macOS"
on:
  push:
    branches: [ master ]
  pull_request:
    # branches: [ master ]

jobs:
  build_libebml:
    name: libebml ${{ matrix.arch }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        arch:   [x86_64, arm64]
    env:
      CMAKE_OPTIONS: -DDEV_MODE=ON -DBUILD_TESTING=ON
    steps:
      - uses: lukka/get-cmake@latest

      - name: Get pushed code
        uses: actions/checkout@v3

      - name: Configure
        run: cmake -S . -B _build ${{ env.CMAKE_OPTIONS }} -DCMAKE_INSTALL_PREFIX:STRING=${GITHUB_WORKSPACE}/_built -DCMAKE_OSX_ARCHITECTURES="${{ matrix.arch }}"

      - name: Build
        run: cmake --build _build --parallel

      - name: Test installation
        run: cmake --install _build --prefix ${GITHUB_WORKSPACE}/_built

      - name: Run tests
        run: |
          if [ $(uname -m) = "${{ matrix.arch }}" ]; then
            ctest --test-dir _build;
          fi
